---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a started container
      lxd_container:
        name: mycontainer
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: simplestreams
          alias: centos/7/amd64
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600
